alias vpdf='qpdfview'
# alias g++14='g++-5 -std=c++14 -Wall -Wextra -Wpedantic'
alias clearhist='cat /dev/null > ~/.bash_history && history -c && clear'
alias rc='vi ~/.bashrc; source ~/.bashrc'
alias list='git branch --list'
