alias vpdf='qpdfview'
alias clearhist='cat /dev/null > ~/.bash_history && history -c && clear'
alias rc='vi ~/.bashrc; source ~/.bashrc'
alias zrc='vi ~/.zshrc; source ~/.zshrc'
alias sizes='du -sh * | sort -h'
alias pinta='LANG=C; /usr/bin/pinta'
